### PR TITLE
Added new LLM options

### PR DESCRIPTION
**Pull request by Sanjay8602**
Added four more LLM options to both sides

### CODE REVIEW

**Comment by ogbanugot** [comment]
Great job @Sanjay8602 , did you test each one?

**Comment by Sanjay8602** [comment]
> Great job @Sanjay8602 , did you test each one?

yes tested

**Comment by ogbanugot** [comment]
Great! Let's get it merged.

**Comment by Sanjay8602** [comment]
> Great! Let's get it merged.

can I deploy?

**Comment by ogbanugot** [comment]
yes please go ahead.

**Pull request merged**
